# NumPy Arrays 

In [17]:
import numpy as np
l = range(1000)
%timeit [i**2 for i in l]

314 µs ± 13.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [18]:
import numpy as np
a = np.arange(1000)
%timeit a**2

1.32 µs ± 2.43 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


3. Create an identity matrix of size 5 (https://en.wikipedia.org/wiki/Identity_matrix) in NumPy.

4. Create a diagonal matrix of size 5 in NumPy. Use **np.diag?** to view the signature of the function. The diagonal should include numbers: 1, 2, 3, 4, 5.

5. Add two arrays together and name is sum.

6. What is the power 3 of sum array? 

In [103]:
import numpy as np
#3
I = np.identity(5)
print(I)

#4
Z = np.diag(1+np.arange(5),k=0)
print(Z)

#5
sum=Z+I
print(sum)

#6
sum*sum*sum

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
[[2. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 4. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 6.]]


array([[  8.,   0.,   0.,   0.,   0.],
       [  0.,  27.,   0.,   0.,   0.],
       [  0.,   0.,  64.,   0.,   0.],
       [  0.,   0.,   0., 125.,   0.],
       [  0.,   0.,   0.,   0., 216.]])

7. Create an array of size (6, 6) and fill it with numbers from 0 to 36 and name it a. 

8. Write code that selects these elements from the array a: 18, 20, 23, 24, 26, 29, 30, 32, 35.

In [68]:
import numpy as np
x = np.arange(36).reshape((6,6))
x

#for i in x[3]:
for i in range(3,6):
    #print(x[i])
    j=0
    g=0
    for j in range(0,4,2):
        print(x[i][j])
    for g in range(5,6):
        print(x[i][g])

18
20
23
24
26
29
30
32
35


9. Create a random vector of size 30 and find the mean value. 

In [94]:
import numpy as np
Z = np.random.random(30)
m = Z.mean()
print(m)

0.505799775257876


10. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal. 

In [95]:
import numpy as np

Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


11. Create a 8x8 matrix and fill it with a checkerboard pattern. Use zero and one to represent black and white respectively.

In [6]:
import numpy as np

Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

12. Create a checkerboard 8x8 matrix using the tile function. 

In [7]:
import numpy as np

Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

Create two matrices of size 5x3 and 3x2 using ones. 
13. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product). 

Hint: Use dot function. 

In [104]:
import numpy as np

Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


14. Create a vector of size 10 with values ranging from 0 to 1, both excluded. 

In [105]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


15. Create a random vector of size 10 and sort it.

In [106]:
import numpy as np
Z = np.random.random(10)
Z.sort()
print(Z)

[0.11655747 0.15026863 0.28849889 0.33239388 0.38959822 0.41613643
 0.50096004 0.50875484 0.81628052 0.87533335]


16. Create random vector of size 10 and replace the maximum value by 0.

In [107]:
import numpy as np
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.70202132 0.68860324 0.23856526 0.62756245 0.71643732 0.48140337
 0.41287738 0.07829439 0.76522294 0.        ]


17. Print the minimum and maximum representable value for each numpy scalar type. (for int32 and int64 as well as float 32 and float 64.

In [109]:
import numpy as np
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


18. Considering a four dimensions array, how to get sum over the last two axis at once? 
hint: Create a random interger array. Dimensionas are 3x4x3x4.

In [110]:
import numpy as np
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[57 61 52 50]
 [57 59 45 59]
 [40 59 61 48]]


19. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? 

In [111]:
import numpy as np
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


20. How to swap the first two rows of an array?

In [91]:
import numpy as np
A = np.arange(25).reshape(5,5)
A
A[[0,1]] = A[[1,0]]
A

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])